import streamlit as st
import base64

# Prepare a local image for the logo. pgn_file (100px each side) is in put the same folder with this source
@st.cache_data
def myLogo(pgn_file):
    # Convert a local pgn image logo file to a base64 string
    with open(pgn_file, 'rb') as f:
        data = f.read()
        logo_base64_text = base64.b64encode(data).decode()
    return logo_base64_text

def main_entry():
    
    # Set page config
    st.set_page_config(page_title="Home Page", page_icon=":camel:", layout='wide', initial_sidebar_state='expanded')
        
    # # Add url image logo into the centre-top of the sidebar and use CSS to custom the logo position
    # logo_image_css = """ <style> [data-testid="stSidebar"] {
    #     background-image: url(https://drive.google.com/uc?id=1ES8IMsDlOCZiXmzl0jyIyTSDUUq8jES8);
    #     background-repeat: no-repeat;
    #     background-size: 100px;
    #     background-position: 100px 5px;} </style> """
    # st.markdown(logo_image_css, unsafe_allow_html=True)
    
    # Add local image logo into the centre-top of the sidebar and use CSS to custom the logo position
    image_logo = myLogo("Leopard_100px.png")
    # Store the logo into SS for other pages (modules)
    st.session_state["image_logo"] = image_logo
    logo_image_css = """ <style> [data-testid="stSidebar"] {
        background-image: url("data:image/png;base64,%s");
        background-repeat: no-repeat;
        background-size: 100px;
        background-position: 100px 5px;} </style> """ % image_logo
    st.markdown(logo_image_css, unsafe_allow_html=True)
    
    # Injecting custom CSS to reduce top space for the title, adjust padding-top value to move the title up
    custom_css = """ <style> .block-container.st-emotion-cache-z5fcl4.ea3mdgi4 {padding-top: 30px;} </style> """
    st.markdown(custom_css, unsafe_allow_html=True)
    
    # Page title. Use markdown to format text rather than using st.title()
    st.markdown("<span style='color: yellow; font-size:45px; font-weight: bold;'> Main Page </span>", unsafe_allow_html=True)
       
    # Add copyright into the sidebar
    st.sidebar.markdown(''' Created with ❤️ by My Thang ''') 
    
    # Text in the main page
    st.markdown(
        """
        ### :green[Welcome to the exploration area]
        *The all in one place for data review and for the highlighting of the exploration prospects*   
        #### Geneal Information
        :cherry_blossom: Overview of the Blocks and Wells   
        #### Well DSTs and Tops Summary
        :cherry_blossom: Summary of the tests and the formation tops
        #### Well Log Cross-Plot
        :cherry_blossom: Review the hostest drilled/drillable prospects
        #### Prospect Review 
        :cherry_blossom: The resources for the G&G activities
    """
    )    
    
if __name__ == "__main__":
    main_entry()
    
# Note:
# The class ".block-container.st-emotion-cache-z5fcl4.ea3mdgi4" is taken from web-inspector tool from the first run od the app.
# This class is auto generated by streamlit itself and is unchanged every time app run.